version: "2.2"

services:

  php:
    container_name: stack_php
    build: 
      context: docker/php
      dockerfile: dev.Dockerfile
    restart: always
    volumes: 
      - ./public/:/var/www/html
    expose:
      - "9000"

  db:
    container_name: stack_mariadb
    image: mariadb
    environment: 
      MYSQL_ROOT_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: dump
    ports: 
      - 3306:3306
    volumes:
      - "db-data:/var/lib/mysql/data"

  nginx:
    container_name: stack_nginx
    image: nginx:1.16.1-alpine
    restart: always
    volumes: 
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf.ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from: 
      - php
    ports: 
      - 80:80

volumes: 
  db-data: {}
