version: "2"

services:

  db:
    image: mariadb:10.1
    container_name: lemp_maria
    restart: always
    volumes: 
      - ./db/initdb/:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=p@ssw0rd123456
      - MYSQL_DATABASE=softeng_db
      - MYSQL_USER=admin_softeng
      - MYSQL_PASSWORD=p@ssw0rd123456

  php:
    image: php:7-fpm-alpine
    container_name: lemp_php
    restart: always
    volumes: 
      - ./public/:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:1.16.1-alpine
    container_name: lemp_nginx
    restart: always
    volumes: 
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf.ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from: 
      - php
    ports: 
      - 80:80